MoviePoint/Models/Producer.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MoviePoint.Models
{
	public class Producer
	{
		public int ProducerId { get; set; }
		public string Name { get; set; }
		public string Bio { get; set; }
		public int Age { get; set; }
		public string ImageUrl { get; set; }

		public virtual List<Movie> Movie { get; set; }
	}

	public class ProducerVM
	{
		public List<Producer> TopProducers { get; set; }
		public List<Producer> AllProducers { get; set; }
	}

	public class ProducerDetails
	{
		public Producer	Producer { get; set; }
		public List<Movie> Movies { get; set; }

	}
}

MoviePoint/Controllers/ProducerController.cs
using MoviePoint.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MoviePoint.Controllers
{
    public class ProducerController : Controller
    {
		private MovieDbContext db = new MovieDbContext(); 
        // GET: Producer
        public ActionResult Index()
        {
            return View(db.Producers.ToList());
        }

		public ActionResult Create()
		{
			return View();
		}

		[HttpPost]
		public ActionResult Create(Producer producer)
		{
			db.Producers.Add(producer);
			db.SaveChanges();
			return RedirectToAction("Index");
		}

		public ActionResult Update(int id)
		{
			return View(db.Producers.Find(id));
		}

		[HttpPost]
		public ActionResult Update(Producer producer)
		{
			db.Entry(producer).State = System.Data.Entity.EntityState.Modified;
			db.SaveChanges();
			return RedirectToAction("Index");
		}

		public ActionResult Delete(int id)
		{
			db.Entry(db.Producers.Find(id)).State = System.Data.Entity.EntityState.Deleted;
			db.SaveChanges();
			return RedirectToAction("Index");
		}

		public ActionResult AddProducer()
		{
			return PartialView();
		}

		[HttpPost]
		public ActionResult AddProducer(Producer producer)
		{
			db.Producers.Add(producer);
			db.SaveChanges();
			return RedirectToAction("ProducerDropDown");
		}

		public ActionResult ProducerDropDown()
		{
			return PartialView(db.Producers.ToList());
		}
	}
}

MoviePoint/Views/Producer/AddProducer.cshtml
@model MoviePoint.Models.Producer
@{
	ViewBag.Title = "AddProducer";
}


<hr />
<br />
<div class="container">
	<div class="border border-dark" style="padding:5%">
		<div class="row">
			<div class="col">
				<h2 class="section_title text-center">Add A New Producer</h2>
			</div>

		</div>
		<br />
		<br />
		<div class="row container">
			<div class="col-6">
				<form method="post" action="/Producer/Create" id="ProducerAddForm" class="form-group">

					<label>Producer Name</label>
					<input name="Name" class="form-control" />
					<br />

					<label>Age</label>
					<input name="Age" class="form-control" /><br />

					<label>Bio</label>
					<textarea name="Bio" class="form-control"></textarea>
					<br />

					<label>Select An Image</label>
					<input name="ImageUrl" type="hidden" id="ProducerImageUrl" />
					<input type="file" id="ProducerImageUpload" accept=".png,.jpg,.jpeg" class="form-control" />
					<br />

					<input type="button" value="Create Producer" id="ProducerCreateBtn" class="btn btn-outline-success" />

				</form>
			</div>

			<div class="col-4" style="padding-left:10%">
				<img src="~/Assets/UploadedImages/placeholder-image.png" width="400" height="300" id="ProducerImage" style="float:left" />
			</div>
			<div class="col-1"></div>
		</div>
	</div>

</div>
<hr />
<script>
	$('#ProducerImageUpload').change(function () {

		var element = this;
		var formData = new FormData();
		var totalFiles = element.files.length;
		for (var i = 0; i < totalFiles; i++) {
			var file = element.files[i];
			formData.append("Photo", file);
		}
		$.ajax({
			type: 'POST',
			url: "/Shared/UploadImage",
			data: formData,
			dataType: 'json',
			contentType: false,
			processData: false
		}).done(function (response) {

			console.log(response);
			if (response.Success == true) {
				$('#ProducerImageUrl').val(response.ImageUrl);
				$('#ProducerImage').attr("src", response.ImageUrl);
			}
		}).fail(function (XMLHttpRequest, textStatus, errorThrown) {
			alert("Failure")
		});
	});



	$('#ProducerCreateBtn').click(function () {
		$.ajax({
			type: 'POST',
			url: "../Producer/AddProducer",
			data: $('#ProducerAddForm').serialize(),
		}).done(function (response) {
			$('#ProducerDropDownContainer').html(" ");
			$('#ProducerDropDownContainer').html(response);
			DeFocus();
			$('#actionContainer').html(" ");


		}).fail(function (XMLHttpRequest, textStatus, errorThrown) {
			alert("Failure")
		});
	});

</script>

MoviePoint/Views/Producer/Create.cshtml
@model MoviePoint.Models.Producer
@{
	ViewBag.Title = "Create";
}
<hr />
<br />
<div class="container">
	<div class="border border-dark" style="padding:5%">
		<div class="row">
			<div class="col">
				<h2 class="section_title text-center">Add A New Producer</h2>
			</div>

		</div>
		<br />
		<br />
		<div class="row container">
			<div class="col-6">
				<form method="post" action="/Producer/Create" id="categoryCreteForm" class="form-group">

					<label>Producer Name</label>
					<input name="Name" class="form-control" />
					<br />

					<label>Age</label>
					<input name="Age" class="form-control" /><br />

					<label>Bio</label>
					<textarea name="Bio" class="form-control"></textarea>
					<br />

					<label>Select An Image</label>
					<input name="ImageUrl" type="hidden" id="ImageUrl" />
					<input type="file" id="imageUpload" accept=".png,.jpg,.jpeg" class="form-control" />
					<br />

					<input type="submit" value="Create Producer" id="fromCreateBtn" class="btn btn-outline-success" />

				</form>
			</div>
		
			<div class="col-4" style="padding-left:10%">
				<img src="~/Assets/UploadedImages/placeholder-image.png" width="400" height="300" id="categoryImage" style="float:left" />
			</div>
			<div class="col-1"></div>
		</div>
	</div>

</div>
<hr />
<script>
	$('#imageUpload').change(function () {

		var element = this;
		var formData = new FormData();
		var totalFiles = element.files.length;
		for (var i = 0; i < totalFiles; i++) {
			var file = element.files[i];
			formData.append("Photo", file);
		}
		$.ajax({
			type: 'POST',
			url: "/Shared/UploadImage",
			data: formData,
			dataType: 'json',
			contentType: false,
			processData: false
		}).done(function (response) {

			console.log(response);
			if (response.Success == true) {
				$('#ImageUrl').val(response.ImageUrl);
				$('#categoryImage').attr("src", response.ImageUrl);
			}
		}).fail(function (XMLHttpRequest, textStatus, errorThrown) {
			alert("Failure")
		});
	});
</script>

MoviePoint/Views/Producer/Delete.cshtml
@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

MoviePoint/Views/Producer/Index.cshtml
@model IEnumerable<MoviePoint.Models.Producer>
@{
	ViewBag.Title = "Index";
}

<hr>
<br />


<div class="container ">

	<div class="border border-dark" style="padding:5%">
		<div>
			<div class="row">
				<div class="col">
					<h2 class="section_title text-center">Our Industry Producers</h2>
				</div>

			</div>
			@Html.ActionLink("Add Producer", "create", "Producer", null, new { @class = "btn btn-sm btn-outline-primary" })
		</div>
		<br />
		<br />
		<div class="container">
			<table class="table table-hover">
				<thead>
					<tr>
						<th>Actor Id</th>
						<th>Name</th>
						<th>Age</th>
						<th>Bio</th>
						<th>Actions</th>
					</tr>
				</thead>
				<tbody>
					@foreach (var item in Model)
					{
						<tr>
							<td>@item.ProducerId</td>
							<td>@item.Name</td>
							<td>@item.Age</td>
							<td>@item.Bio</td>
							<td>
								<div>
									@Html.ActionLink("Edit", "Update", "Producer", new { id = item.ProducerId }, new { @class = "btn btn-sm btn-outline-warning" })
									@Html.ActionLink("Deleted", "Delete", "Producer", new { id = item.ProducerId }, new { @class = "btn btn-sm btn-outline-danger" })
								</div>
							</td>
						</tr>
					}
				</tbody>
			</table>
		</div>

	</div>


</div>
<hr>

MoviePoint/Views/Producer/ProducerDropDown.cshtml
@model IEnumerable<MoviePoint.Models.Producer>
@{
	ViewBag.Title = "ProducerDropDown";
}



<select class="form-control" name="ProducerId" >
	@foreach (var item in Model)
	{
		<option value="@item.ProducerId">@item.Name</option>
	}
</select>

MoviePoint/Views/Producer/Update.cshtml
@model MoviePoint.Models.Producer
@{
	ViewBag.Title = "Update";
}
<hr />
<br />
<div class="container">

	<div class="border border-dark" style="padding:5%">

		<div class="row">
			<div class="col">
				<h2 class="section_title text-center">Update This Producer</h2>
			</div>

		</div>
		<br />
		<br />
		<div class="row">
			<div class="col-6">
				<form method="post" action="/Producer/Update" id="categoryUpdateForm" class="form-group">

					<input type="hidden" name="ProducerId" value="@Model.ProducerId" />

					<label>Producer Name</label>
					<input name="Name" class="form-control" value="@Model.Name" />
					<br />
					<label>Age</label>
					<input name="Age" class="form-control" value="@Model.Age" />
					<br />

					<label>Bio</label>
					<textarea name="Bio" class="form-control">@Model.Bio</textarea>
					<br />

					<label>Select An Image</label>
					<input name="ImageUrl" type="hidden" id="ImageUrl" value="@Model.ImageUrl" />
					<input type="file" id="imageUpload" accept=".png,.jpg,.jpeg" class="form-control" />

					<br />

					<input type="submit" id="updateBtn" value="Update Producer" class="btn btn-sm btn-outline-primary" />

				</form>

			</div>
			<div class="col-1">

			</div>
			<div class="col-4">
				<img src="@Model.ImageUrl" width="400" height="300" id="categoryImage" />
			</div>
			<div class="col-1">

			</div>
		</div>
	</div>

	</div>
	<hr />
	<script>
		$('#imageUpload').change(function () {
			var element = this;
			var formData = new FormData();
			var totalFiles = element.files.length;
			for (var i = 0; i < totalFiles; i++) {
				var file = element.files[i];
				formData.append("Photo", file);
			}
			$.ajax({
				type: 'POST',
				url: "/Shared/UploadImage",
				data: formData,
				dataType: 'json',
				contentType: false,
				processData: false
			}).done(function (response) {
				debugger;
				console.log(response);
				if (response.Success == true) {
					$('#ImageUrl').val(response.ImageUrl);
					$('#categoryImage').attr("src", response.ImageUrl);
				}
			}).fail(function (XMLHttpRequest, textStatus, errorThrown) {
				alert("Failure")
			});
		});
	</script>