MoviePoint/Models/Actor.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MoviePoint.Models
{
	public class Actor
	{
		public int ActorId { get; set; }
		public string Name { get; set; }
		public string Bio { get; set; }
		public int Age { get; set; }
		public string ImageUrl { get; set; }

		public virtual List<ActorToMovie> ActorToMovie { get; set; }
	}

	public class ActorVM
	{
		public List<Actor> TopActors { get; set; }
		public List<Actor> AllActors { get; set; }
	}

	public class ActorDetails
	{
		public Actor Actor { get; set; }
		public List<Movie> Movies { get; set; }

	}
}

MoviePoint/Controllers/ActorController.cs
using MoviePoint.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MoviePoint.Controllers
{
    public class ActorController : Controller
    {
		private MovieDbContext db = new MovieDbContext();
        // GET: Actor
        public ActionResult Index()
        {
            return View(db.Actors.ToList());
        }

		public ActionResult Create()
		{
			return View();
		}

		[HttpPost]
		public ActionResult Create(Actor actor)
		{
			db.Actors.Add(actor);
			db.SaveChanges();
			return RedirectToAction("Index");
		}

		public ActionResult Update(int id)
		{
			return View(db.Actors.Find(id));
		}

		[HttpPost]
		public ActionResult Update(Actor actor)
		{
			db.Entry(actor).State = System.Data.Entity.EntityState.Modified;
			db.SaveChanges();
			return RedirectToAction("Index");
		}
		
		public ActionResult Delete(int id)
		{
			var actor = db.Actors.Find(id);
			db.Entry(actor).State = System.Data.Entity.EntityState.Deleted;
			db.SaveChanges();
			return RedirectToAction("Index");
		}
		[HttpGet]
		public ActionResult AddActor()
		{
			return PartialView();
		}

		[HttpPost]
		public ActionResult AddActor(Actor actor)
		{
			db.Actors.Add(actor);
			db.SaveChanges();
			return RedirectToAction("ActorDropDown");
		}

		public ActionResult ActorDropDown()
		{
			return PartialView(db.Actors.ToList());
		}
	}
}

MoviePoint/Views/Actor/ActorDropDown.cshtml
@model IEnumerable<MoviePoint.Models.Actor>
@{
    ViewBag.Title = "ActorDropDown";
}

<select class="form-control" name="ActorsIds" multiple>
	@foreach (var item in Model)
	{
		<option value="@item.ActorId">@item.Name</option>
	}
</select>

MoviePoint/Views/Actor/AddActor.cshtml
@model MoviePoint.Models.Actor
@{
	ViewBag.Title = "AddActor";
}

<hr><br />
<div class="container">
	<div class="border border-dark" style="padding:5%">
		<div class="row">
			<div class="col">
				<h2 class="section_title text-center">Add A New Actor</h2>
			</div>

		</div>
		<br />
		<br />
		<div class="row container">
			<div class="col-6">
				<form method="post" action="/Actor/Create" id="ActorAddForm" class="form-group">

					<label>Actor Name</label>
					<input type="text" name="Name" class="form-control" />
					<br />

					<label>Age</label>
					<input type="number" name="Age" class="form-control" /><br />

					<label>Bio</label>
					<textarea name="Bio" class="form-control"></textarea>
					<br />

					<label>Select An Image</label>
					<input name="ImageUrl" type="hidden" id="ImageUrlAddActor" />
					<input type="file" id="imageUploadAddActor" accept=".png,.jpg,.jpeg" class="form-control" />
					<br />

					<input type="button" value="Create Actor" id="AddActorbtn" class="btn btn-sm btn-outline-success" />

				</form>
			</div>

			<div class="col-4" style="padding-left:10%">
				<img src="~/Assets/UploadedImages/placeholder-image.png" width="400" height="300" id="AddActorImage" style="float:left" />
			</div>
			<div class="col-1"></div>
		</div>
	</div>



</div>

<hr />
<script>
	$('#imageUploadAddActor').change(function () {

		var element = this;
		var formData = new FormData();
		var totalFiles = element.files.length;
		for (var i = 0; i < totalFiles; i++) {
			var file = element.files[i];
			formData.append("Photo", file);
		}
		$.ajax({
			type: 'POST',
			url: "/Shared/UploadImage",
			data: formData,
			dataType: 'json',
			contentType: false,
			processData: false
		}).done(function (response) {

			console.log(response);
			if (response.Success == true) {
				$('#ImageUrlAddActor').val(response.ImageUrl);
				$('#AddActorImage').attr("src", response.ImageUrl);
			}
		}).fail(function (XMLHttpRequest, textStatus, errorThrown) {
			alert("Failure")
		});
	});


	

	$('#AddActorbtn').click(function () {
		$.ajax({
			type: 'POST',
			url: "../Actor/AddActor",
			data: $('#ActorAddForm').serialize(),
		}).done(function (response) {
			$('#actorDropDownContainer').html(" ");
			$('#actorDropDownContainer').html(response);
			DeFocus();
			$('#actionContainer').html(" ");

			
		}).fail(function (XMLHttpRequest, textStatus, errorThrown) {
			alert("Failure")
		});
	});
</script>

MoviePoint/Views/Actor/Create.cshtml
@model MoviePoint.Models.Actor
@{
	ViewBag.Title = "Create";
}
<hr><br />
<div class="container">
	<div class="border border-dark" style="padding:5%">
		<div class="row">
			<div class="col">
				<h2 class="section_title text-center">Add A New Actor</h2>
			</div>

		</div>
		<br />
		<br />
		<div class="row container">
			<div class="col-6">
				<form method="post" action="/Actor/Create" id="categoryCreteForm" class="form-group">

					<label>Actor Name</label>
					<input type="text" name="Name" class="form-control" />
					<br />

					<label>Age</label>
					<input type="number" name="Age" class="form-control" /><br />

					<label>Bio</label>
					<textarea name="Bio" class="form-control"></textarea>
					<br />

					<label>Select An Image</label>
					<input name="ImageUrl" type="hidden" id="ImageUrl" />
					<input type="file" id="imageUpload" accept=".png,.jpg,.jpeg" class="form-control" />
					<br />

					<input type="submit" value="Create Actor" id="fromCreateBtn" class="btn btn-sm btn-outline-success" />

				</form>
			</div>
			
			<div class="col-4" style="padding-left:10%">
				<img src="~/Assets/UploadedImages/placeholder-image.png" width="400" height="300" id="categoryImage" style="float:left" />
			</div>
			<div class="col-1"></div>
		</div>
	</div>
	


</div>

<hr />
<script>
	$('#imageUpload').change(function () {

		var element = this;
		var formData = new FormData();
		var totalFiles = element.files.length;
		for (var i = 0; i < totalFiles; i++) {
			var file = element.files[i];
			formData.append("Photo", file);
		}
		$.ajax({
			type: 'POST',
			url: "/Shared/UploadImage",
			data: formData,
			dataType: 'json',
			contentType: false,
			processData: false
		}).done(function (response) {

			console.log(response);
			if (response.Success == true) {
				$('#ImageUrl').val(response.ImageUrl);
				$('#categoryImage').attr("src", response.ImageUrl);
			}
		}).fail(function (XMLHttpRequest, textStatus, errorThrown) {
			alert("Failure")
		});
	});
</script>

MoviePoint/Views/Actor/Delete.cshtml
@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

MoviePoint/Views/Actor/Index.cshtml
@model IEnumerable<MoviePoint.Models.Actor>
@{
	ViewBag.Title = "Index";
}


<hr />
<br />
<div class="container">
	<div class="border border-dark" style="padding:5%">
		<div>

			<div class="row">
				<div class="col">
					<h2 class="section_title text-center">Popular Actors</h2>
				</div>
			</div>
			@Html.ActionLink("Add Actor", "create", "Actor", null, new { @class = "btn btn-outline-primary" })
		</div>
		<br /><br />
		<div>
			<table class="table table-borderless">
				<thead>
					<tr>
						<th>Actor Id</th>
						<th>Name</th>
						<th>Age</th>
						<th>Bio</th>
						<th>Actions</th>
					</tr>
				</thead>
				<tbody>
					@foreach (var item in Model)
					{
						<tr>
							<td>@item.ActorId</td>
							<td>@item.Name</td>
							<td>@item.Age</td>
							<td>@item.Bio</td>
							<td>
								<div>
									@Html.ActionLink(" Edit", "Update", "Actor", new { id = item.ActorId }, new { @class = "btn btn-sm btn-outline-warning" })
									@Html.ActionLink(" Delete", "Delete", "Actor", new { id = item.ActorId }, new { @class = "btn btn-sm btn-outline-danger" })
								</div>
							</td>
						</tr>
					}
				</tbody>
			</table>
		</div>
	</div>

</div>

<hr />

MoviePoint/Views/Actor/Update.cshtml
@model MoviePoint.Models.Actor
@{

				ViewBag.Title = "Update";
}
<hr />
<br />
<div class="container">
	<div class="border border-dark" style="padding:5%">
		<div class="row">
			<div class="col">
				<h2 class="section_title text-center">Edit This Actor</h2>
			</div>
		</div>
		<br />
		<br />
		<div class="row">
			<div class="col-6">
				<form method="post" action="/Actor/Update" id="categoryUpdateForm" class="form-group">

					<input type="hidden" name="ActorId" value="@Model.ActorId" />

					<label>Actor Name</label>
					<input name="Name" class="form-control" value="@Model.Name" />
					<br />
					<label>Age</label>
					<input name="Age" class="form-control" value="@Model.Age" />
					<br />

					<label>Bio</label>
					<textarea name="Bio" class="form-control">@Model.Bio</textarea>

					<br />

					<label>Select An Image</label>
					<input name="ImageUrl" type="hidden" id="ImageUrl" value="@Model.ImageUrl" />
					<input type="file" id="imageUpload" accept=".png,.jpg,.jpeg" class="form-control" />

					<br />

					<input type="submit" id="updateBtn" value="Update" class="btn btn-sm btn-outline-primary" />

				</form>

			</div>
			<div class="col-1">

			</div>
			<div class="col-4">
				<img src="@Model.ImageUrl" width="400" height="300" id="categoryImage" />
			</div>
			<div class="col-1">

			</div>
		</div>
	</div>

</div>
<hr />
<script>
    $('#imageUpload').change(function () {
        var element = this;
        var formData = new FormData();
        var totalFiles = element.files.length;
        for (var i = 0; i < totalFiles; i++) {
            var file = element.files[i];
            formData.append("Photo", file);
        }
        $.ajax({
            type: 'POST',
            url: "/Shared/UploadImage",
            data: formData,
            dataType: 'json',
            contentType: false,
            processData: false
        }).done(function (response) {
            debugger;
            console.log(response);
            if (response.Success == true) {
                $('#ImageUrl').val(response.ImageUrl);
                $('#categoryImage').attr("src", response.ImageUrl);
            }
        }).fail(function (XMLHttpRequest, textStatus, errorThrown) {
            alert("Failure")
        });
	});
</script>